apiVersion: v1
kind: Service
metadata:
  annotations:
     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
     name: cms-redis
  name: cms-redis-svc
spec:
  type: NodePort
  ports:
   - port: 6379
  selector:
     name: cms-redis